version: '3' 
services:
  db: 
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=oxossi12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    environment:
      - PGHOST=db
      - PGUSER=postgres
    volumes:
      - .:/nanna-martins
    ports:
      - "3000:3000"
    depends_on:
      - db
