version: '3'
services:
  web:
    build: .
    environment:
      NOAUTH: 1
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/var/www/nanna-martins
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: "postgres"
