default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5)  %>
  host: postgres
  username: postgres
  password: postgres

development:
  <<: *default
  pool: false
  database: nanna-martins_development

test:
  <<: *default
  pool: false
  database: nanna-martins_test

production:
  <<: *default
  pool: false
  database: nanna-martins
