#!/bin/bash -e

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

$DOCKER_COMPOSE build && \
$DOCKER_COMPOSE run --service-ports $(app_env) --rm -T web bash -c "rails db:drop db:create db:migrate db:seed"
